"""add write_access to api_keys

Revision ID: e5cb0713f871
Revises: d5c2ef1cd1fb
Create Date: 2026-08-08 00:40:53.889067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'e5cb0713f871'
down_revision: Union[str, None] = 'd5c2ef1cd1fb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('api_keys', sa.Column('write_access', sa.Boolean(), nullable=False, server_default=sa.false()))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('api_keys', 'write_access')
    # ### end Alembic commands ###
